export const surpriseMePrompts = [
    "an armchair in the shape of an avocado",
    "a surrealist dream-like oil painting by Salvador Dalí of a cat playing checkers",
    "teddy bears shopping for groceries in Japan, ukiyo-e",
    "an oil painting by Matisse of a humanoid robot playing chess",
    "panda mad scientist mixing sparkling chemicals, digital art",
    "a macro 35mm photograph of two mice in Hawaii, they're each wearing tiny swimsuits and are carrying tiny surf boards, digital art",
    "3D render of a cute tropical fish in an aquarium on a dark blue background, digital art",
    "an astronaut lounging in a tropical resort in space, vaporwave",
    "an oil painting portrait of a capybara wearing medieval royal robes and an ornate crown on a dark background",
    "a stained glass window depicting a hamburger and french fries",
    "a pencil and watercolor drawing of a bright city in the future with flying cars",
    "a sunlit indoor lounge area with a pool with clear water and another pool with translucent pastel pink water, next to a big window, digital art",
    "a fortune-telling shiba inu reading your fate in a giant hamburger, digital art",
    '"a sea otter with a pearl earring" by Johannes Vermeer',
    "an oil pastel drawing of an annoyed cat in a spaceship",
    "a painting of a fox in the style of Starry Night",
    "a bowl of soup that looks like a monster, knitted out of wool",
    "A plush toy robot sitting against a yellow wall",
    "A synthwave style sunset above the reflecting water of the sea, digital art",
    "Two futuristic towers with a skybridge covered in lush foliage, digital art",
    "A 3D render of a rainbow colored hot air balloon flying above a reflective lake",
    "A comic book cover of a superhero wearing headphones",
    "A centered explosion of colorful powder on a black background",
    "A photo of a Samoyed dog with its tongue out hugging a white Siamese cat",
    "A photo of a white fur monster standing in a purple room",
    "A photo of Michelangelo's sculpture of David wearing headphones djing",
    "A Samurai riding a Horse on Mars, lomography.",
    "A modern, sleek Cadillac drives along the Gardiner expressway with downtown Toronto in the background, with a lens flare, 50mm photography",
    "A realistic photograph of a young woman with blue eyes and blonde hair",
    "A man standing in front of a stargate to another dimension",
    "Spongebob Squarepants in the Blair Witch Project",
    "A velociraptor working at a hotdog stand, lomography",
    "A man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs, 50mm lens",
    "A BBQ that is alive, in the style of a Pixar animated movie",
    "A futuristic cyborg dance club, neon lights",
    "The long-lost Star Wars 1990 Japanese Anime",
    "A hamburger in the shape of a Rubik’s cube, professional food photography",
    "A Synthwave Hedgehog, Blade Runner Cyberpunk",
    "An astronaut encountering an alien life form on a distant planet, photography",
    "A Dinosaur exploring Cape Town, photography",
    "A Man falling in Love with his Computer, digital art",
    "A photograph of a cyborg exploring Tokyo at night, lomography",
    "Dracula walking down the street of New York City in the 1920s, black and white photography",
    "Synthwave aeroplane",
    "A man wanders through the rainy streets of Tokyo, with bright neon signs, 50mm",
    "A Space Shuttle flying above Cape Town, digital art",
    "A steampunk-inspired teapot with mechanical legs and arms",
    "A psychedelic mushroom forest with neon-colored foliage, digital art",
    'Vincent van Gogh\'s "Starry Night" reimagined with a galactic theme',
    "A whimsical carousel with mythical creatures as rideable animals",
    "A time-traveling cat in a top hat and monocle, digital art",
    "A vintage typewriter surrounded by floating words and letters, surreal digital art",
    "A secret garden hidden inside an old grandfather clock",
    "A cybernetic octopus playing a grand piano in an underwater cave",
    "A graffiti mural of an astronaut breakdancing on the moon",
    "A Victorian-era airship cruising through a cotton candy sky",
    "A cyberpunk cityscape with holographic billboards and flying cars, digital art",
    "A serene Zen garden with bonsai trees and a koi fish pond",
    "A haunted lighthouse with a ghostly figure at the top",
    "A whimsical treehouse in the middle of a colorful rainforest",
    "A surrealistic painting of a melting clock draped over a tree",
    "A futuristic coffee shop with robotic baristas, digital art",
    "A magical library with floating books and candles",
    "A post-apocalyptic wasteland with a lone survivor and their trusty robot companion",
    "A vintage camera taking a selfie with a smartphone",
    "A serene underwater world with bioluminescent sea creatures",
    "A dragon perched on a mountaintop covered in crystal ice, digital art",
    "A giant rubber duck floating in a city river",
    "A medieval castle floating in the sky with hot air balloons tethered to it",
    'A time-traveling phone booth like the one from "Bill and Ted\'s Excellent Adventure"',
    "A cityscape of New York City made entirely of candy and sweets",
    "A cybernetic forest with neon trees and robotic wildlife, digital art",
    "A wizard's laboratory filled with magical potions and spell books",
    "A giant bookshelf as a skyscraper, with books for windows",
    "A mysterious door in the middle of a dense forest",
    "A surrealistic painting of an elephant with elongated legs",
    "A floating island with a waterfall pouring into the sky",
    "A Viking longship sailing through the stars, digital art",
    "A candy cane road winding through a gingerbread village",
    "A spaceship made entirely of recycled materials, digital art",
    "A giant rubber ducky racing a flock of flamingos in a bathtub",
    "A futuristic underwater city with transparent domes, digital art",
    "A medieval jousting tournament with knights riding on mechanical horses",
    "A steampunk-inspired hot air balloon festival in the clouds",
    "A dragon breathing fire onto a frozen lake, creating a fiery spectacle, digital art",
    "A carnival on the moon with zero-gravity rides",
    "A surrealistic painting of a melting ice cream cone",
    "A cybernetic jungle with robotic parrots and electronic vines, digital art",
    "A library with doors that lead to different fictional worlds",
    "A magical marketplace selling potions, spell ingredients, and mythical creatures",
    'A time-traveling Delorean from "Back to the Future"',
    "A city skyline with skyscrapers made of playing cards",
    "A futuristic racing track for hoverboard competitions",
    "A psychedelic dragonfly in a rainbow-colored forest, digital art",
    "A retro arcade with classic games and neon lights",
    "A wizard's tower with a swirling vortex at the top",
];
